config/routes.rb
Rails.application.routes.draw do
  resources :answers, only: :create
  resources :questions, only: :show
  resources :users, only: :create
  delete :logout, to: 'sessions#destroy'
  get :login, to: 'pages#login'
  post :login, to: 'sessions#create'
  get :intro, to: 'pages#intro'
  get :results, to: 'pages#results'
  root "pages#home"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :options
end

app/models/user.rb
class User < ApplicationRecord
  validates :nickname, uniqueness: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def create
    options_ids_animals = Option.where(id: answer_params[:ordered_options_ids]).pluck(:id, :animal).to_h

    animals_order = []

    answer_params[:ordered_options_ids].each do |option_id|
      animals_order << options_ids_animals[option_id.to_i]
    end

    answer = Answer.find_by(user: current_user, question_id: answer_params[:question_id])

    if answer.present?
      answer.update!(animals_order: animals_order)
    else
      Answer.create!(animals_order: animals_order, user: current_user, question_id: answer_params[:question_id])
    end

    next_question = Question.find_by(id: answer_params[:question_id].to_i + 1)
    return redirect_to next_question if next_question.present?

    redirect_to results_path
  end

  private

  def answer_params
    params.require(:answer).permit(:question_id, ordered_options_ids: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :user_authenticated?

  def current_user
    @_current_user ||= User.find(session[:id])
  end

  def user_authenticated?
    session[:id].present?
  end

  def authenticate_user!
    redirect_to root_path unless user_authenticated?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:intro, :results]

  def home
    @user = User.new
  end

  def login
    @user = User.new
  end

  def intro
    @first_question = Question.first
  end

  def results
    current_user.show_results = true
    current_user.save!

    users_answers = Answer.where(user: current_user)

    users_answers.each do |answer|
      animals_order = answer.animals_order
      while animals_order.present?
        animal = animals_order.shift
        current_user.results[animal] += animals_order.length
      end
    end

    current_user.results = Hash[current_user.results.sort_by{|k, v| v}.reverse]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: :show

  def show
    @answer = Answer.new
    @options = @question.options.shuffle
    @previous_question = Question.find_by(id: @question.id.to_i - 1)
  end

  private

  def set_question
    @question = Question.includes(:options).find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(nickname: permitted_nickname)

    if @user.present?
      session[:id] = @user.id
      redirect_to results_path
    else
      @nickname_not_found = true
      render 'pages/login', status: :unprocessable_entity
    end
  end

  def destroy
    session[:id] = nil

    redirect_to root_path
  end

  private

  def permitted_nickname
    params.permit(:nickname)[:nickname]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(user_params)

    if @user.save
      session[:id] = @user.id
      redirect_to intro_path
    else
      render 'pages/home', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/answers/create.html.haml
%h1 Answers#create
%p Find me in app/views/answers/create.html.haml

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Core Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('logo.png') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.haml
.cut-container.cut-container__left-cut
  - if !user_authenticated?
    - invalid = @user.errors.include?(:nickname)

    .intro-header
      %span Lev.
      %span Bobor.
      %span Zlatý retríver?
      %span Tuleň.

    = form_with model: @user, class: 'flex-column' do |f|
      - if invalid
        .label
          Nickname je už žiaľ obsadený. :(
      - else
        = f.label :nickname, class: 'label'
      = f.text_field :nickname, class: "pill pill__white pill__input #{'error' if invalid}"
      = f.submit 'Začať test', class: 'pill pill__black'

    = link_to 'Pozrieť si výsledok', login_path, class: 'small-link'
  - else
    .disclaimer
      .intro-header= "#{current_user.nickname},"
      .text
        nie je veľa tých, ktorým sa podarilo objaviť túto časť aplikácie.

        %p
          Keďže tu však si, tak Tebe špeciálne prajeme ešte príjemný zvyšok tréningu!
        %p
          Vďaka, že aj vďaka Tebe môžu mladí ľudia spoznávať Jeho.

        = link_to '(Odhlásiť sa)', logout_path, data: { "turbo-method": :delete }, class: 'small-link'

app/views/pages/intro.html.haml
.container
  .instruction
    .seal
      = image_tag 'seal.png', width: 35
    .text
      Zoraď nasledovné vlastnosti podľa toho, ako veľmi na teba “sedia”. Čím viac ťa daná vlastnosť opisuje, tým vyššie ju umiestni.”

  %ul{ data: { controller: 'sortable' } }
    %li.pill.pill__option Pokorný
    %li.pill.pill__option Usmievavý
    %li.pill.pill__option Pohľadný
    %li.pill.pill__option Múdry

  .page-end
    %p
      Toto bola cvičná otázka, samozrejme.
    = link_to 'Začať kvíz', @first_question, class: 'pill pill__black'

app/views/pages/login.html.haml
.cut-container.cut-container__right-cut
  - if !user_authenticated?

    .intro-header
      %span Lev,
      %span šatník..
      %span či ako to bolo?

    = form_with url: login_path, method: :post, class: 'flex-column' do |f|
      - if @nickname_not_found
        .label
          Výsledky pre takýto nick sme nenašli. :((
      - else
        = f.label :nickname, class: "label"
      = f.text_field :nickname, class: "pill pill__white pill__input"
      = f.submit 'Pozrieť si výsledok', class: 'pill pill__black'

    = link_to 'Urobiť si test', root_path, class: 'small-link'

app/views/pages/results.html.haml
- max_points = current_user.results.to_a.second[1]

.container
  .main-animal-cover
    = image_tag "#{current_user.results.first[0]}.png"
    .points= current_user.results.first[1]

  .results
    - current_user.results.each_with_index do |result, index|
      - next if index == 0
      - animal, points = result
      .other-animal
        .logo= image_tag "#{animal}.png", width: 50
        .line{ style: "width: #{60 * points / max_points }%;" }
        .points= points





  = link_to 'Odhlásiť sa', logout_path, data: { "turbo-method": :delete }, class: 'small-link'

app/views/questions/show.html.haml
- call_to_action = @question.id == 19 ? 'Vyhodnoť test' : 'Ďalšia otázka'

.container
  .counter
    .big-number= @question.id
    .slash= '/'
    .small-number 19


  %ul{ data: { controller: 'sortable' } }
    - @options.each do |option|
      %li.option.pill.pill__option{ data: { option_id: option.id } }= option.text

  = form_with model: @answer do |f|
    - @options.each do |option|
      = f.hidden_field :ordered_options_ids, multiple: true, value: option.id
      = f.hidden_field :question_id, value: @question.id
    - if @previous_question
      .half-pill
        = link_to '&larr;'.html_safe, @previous_question, class: 'left' if @previous_question
        = f.submit call_to_action, class: 'right'
    - else
      = f.submit call_to_action, class: 'pill pill__black'